// Package compat regenerates the v1 entry files (current-task.md, knowledge.md, decisions.md)
// as short generated indexes, so agents following v1 instructions still find their way.
package compat

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/innaka-tech/ai-toolkit/v2/internal/adr"
	"github.com/innaka-tech/ai-toolkit/v2/internal/fsx"
	"github.com/innaka-tech/ai-toolkit/v2/internal/knowledge"
	"github.com/innaka-tech/ai-toolkit/v2/internal/project"
	"github.com/innaka-tech/ai-toolkit/v2/internal/session"
	"github.com/innaka-tech/ai-toolkit/v2/internal/task"
)

const banner = "<!-- Generated by aitk. Do not edit. Run `aitk brief` for the full picture. -->\n\n"

// GeneratedMarker identifies files aitk generates and may overwrite.
const GeneratedMarker = "<!-- Generated by aitk"

// WriteGenerated writes path only when it is absent or was generated by aitk, so hand-written
// files are never overwritten. It reports whether the file is aitk's (written or skipped).
func WriteGenerated(path string, content []byte) (bool, error) {
	if b, err := os.ReadFile(path); err == nil && !strings.Contains(string(b), GeneratedMarker) {
		return false, nil
	}
	return true, fsx.WriteFile(path, content, 0o644)
}

// HandWritten lists generated-index paths that hold hand-written content aitk leaves alone.
func HandWritten(p *project.Project) []string {
	var out []string
	for _, rel := range []string{"current-task.md", "knowledge.md", "decisions.md", "handoff.md"} {
		if b, err := os.ReadFile(p.Path(project.DocsAI, rel)); err == nil && !strings.Contains(string(b), GeneratedMarker) {
			out = append(out, project.DocsAI+"/"+rel)
		}
	}
	return out
}

// Write regenerates all compatibility indexes.
func Write(p *project.Project) error {
	for _, f := range []func(*project.Project) error{currentTask, knowledgeIndex, decisions, goals} {
		if err := f(p); err != nil {
			return err
		}
	}
	return nil
}

func currentTask(p *project.Project) error {
	var b strings.Builder
	b.WriteString("# Current task\n\n" + banner)
	tasks, _ := task.List(p)
	active := session.Load(p).Active()
	n := 0
	for _, t := range tasks {
		if t.Status == task.Done || t.Status == task.Cancelled {
			continue
		}
		mark := ""
		if strings.EqualFold(t.ID, active) {
			mark = " ← active in this worktree"
		}
		fmt.Fprintf(&b, "- %s [%s] %s — %s%s\n", t.ID, t.Status, t.Title, t.File, mark)
		n++
	}
	if n == 0 {
		b.WriteString("No open tasks. Create one: `aitk task new \"<title>\"`.\n")
	}
	_, err := WriteGenerated(p.Path(project.DocsAI, "current-task.md"), []byte(b.String()))
	return err
}

func knowledgeIndex(p *project.Project) error {
	var b strings.Builder
	b.WriteString("# Knowledge\n\n" + banner + "Entries live in docs/ai/knowledge/<topic>.md. Search: `aitk knowledge search \"<query>\"`.\n\n")
	count := map[string]int{}
	var topics []string
	for _, e := range knowledge.LoadAll(p) {
		if count[e.Topic] == 0 {
			topics = append(topics, e.Topic)
		}
		count[e.Topic]++
	}
	for _, t := range topics {
		fmt.Fprintf(&b, "- [%s](knowledge/%s.md): %d entries\n", t, t, count[t])
	}
	_, err := WriteGenerated(p.Path(project.DocsAI, "knowledge.md"), []byte(b.String()))
	return err
}

func decisions(p *project.Project) error {
	var b strings.Builder
	b.WriteString("# Decisions\n\n" + banner + "Decisions are ADRs in docs/adr/. New: `aitk adr new \"<title>\"`.\n\n")
	for _, r := range adr.List(p) {
		fmt.Fprintf(&b, "- ADR-%04d [%s] %s — ../../%s\n", r.Number, r.Status, r.Title, r.File)
	}
	_, err := WriteGenerated(p.Path(project.DocsAI, "decisions.md"), []byte(b.String()))
	return err
}

func goals(p *project.Project) error {
	raw, err := os.ReadFile(p.Path(project.StateFile))
	if err != nil {
		return nil
	}
	var st struct {
		Goals []struct{ ID, Title, Status, Parent string } `json:"goals"`
	}
	if json.Unmarshal(raw, &st) != nil {
		return nil
	}
	tasks, _ := task.List(p)
	var b strings.Builder
	b.WriteString("# Goals\n\n<!-- Generated by aitk from ai-state.json goals. Manage with aitk goal add|status. -->\n\n")
	if len(st.Goals) == 0 {
		b.WriteString("No goals yet: `aitk goal add \"<outcome>\"`.\n")
	}
	for _, g := range st.Goals {
		n, done := 0, 0
		for _, t := range tasks {
			if strings.EqualFold(t.Goal, g.ID) && t.Status != task.Cancelled {
				n++
				if t.Status == task.Done {
					done++
				}
			}
		}
		parent := ""
		if g.Parent != "" {
			parent = " (under " + g.Parent + ")"
		}
		fmt.Fprintf(&b, "- %s [%s] %s%s — %d/%d tasks done\n", g.ID, g.Status, g.Title, parent, done, n)
	}
	_, err = WriteGenerated(p.Path(project.DocsAI, "goals.md"), []byte(b.String()))
	return err
}
