// Package compat regenerates the v1 entry files (current-task.md, knowledge.md, decisions.md)
// as short generated indexes, so agents following v1 instructions still find their way.
package compat

import (
	"fmt"
	"strings"

	"github.com/innaka-tech/ai-toolkit/internal/adr"
	"github.com/innaka-tech/ai-toolkit/internal/fsx"
	"github.com/innaka-tech/ai-toolkit/internal/knowledge"
	"github.com/innaka-tech/ai-toolkit/internal/project"
	"github.com/innaka-tech/ai-toolkit/internal/session"
	"github.com/innaka-tech/ai-toolkit/internal/task"
)

const banner = "<!-- Generated by aitk. Do not edit. Run `aitk brief` for the full picture. -->\n\n"

// Write regenerates all compatibility indexes.
func Write(p *project.Project) error {
	for _, f := range []func(*project.Project) error{currentTask, knowledgeIndex, decisions} {
		if err := f(p); err != nil {
			return err
		}
	}
	return nil
}

func currentTask(p *project.Project) error {
	var b strings.Builder
	b.WriteString("# Current task\n\n" + banner)
	tasks, _ := task.List(p)
	active := session.Load(p).Active()
	n := 0
	for _, t := range tasks {
		if t.Status == task.Done || t.Status == task.Cancelled {
			continue
		}
		mark := ""
		if strings.EqualFold(t.ID, active) {
			mark = " ← active in this worktree"
		}
		fmt.Fprintf(&b, "- %s [%s] %s — %s%s\n", t.ID, t.Status, t.Title, t.File, mark)
		n++
	}
	if n == 0 {
		b.WriteString("No open tasks. Create one: `aitk task new \"<title>\"`.\n")
	}
	return fsx.WriteFile(p.Path(project.DocsAI, "current-task.md"), []byte(b.String()), 0o644)
}

func knowledgeIndex(p *project.Project) error {
	var b strings.Builder
	b.WriteString("# Knowledge\n\n" + banner + "Entries live in docs/ai/knowledge/<topic>.md. Search: `aitk knowledge search \"<query>\"`.\n\n")
	count := map[string]int{}
	var topics []string
	for _, e := range knowledge.LoadAll(p) {
		if count[e.Topic] == 0 {
			topics = append(topics, e.Topic)
		}
		count[e.Topic]++
	}
	for _, t := range topics {
		fmt.Fprintf(&b, "- [%s](knowledge/%s.md): %d entries\n", t, t, count[t])
	}
	return fsx.WriteFile(p.Path(project.DocsAI, "knowledge.md"), []byte(b.String()), 0o644)
}

func decisions(p *project.Project) error {
	var b strings.Builder
	b.WriteString("# Decisions\n\n" + banner + "Decisions are ADRs in docs/adr/. New: `aitk adr new \"<title>\"`.\n\n")
	for _, r := range adr.List(p) {
		fmt.Fprintf(&b, "- ADR-%04d [%s] %s — ../../%s\n", r.Number, r.Status, r.Title, r.File)
	}
	return fsx.WriteFile(p.Path(project.DocsAI, "decisions.md"), []byte(b.String()), 0o644)
}
