package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// Reference renders docs/reference/cli.md from the command tree, so the reference
// can never drift from the code (a test fails when the committed file is stale).
func Reference() string {
	a := &app{stdout: io.Discard, stderr: io.Discard}
	root := a.root()
	var b strings.Builder
	b.WriteString("# CLI reference\n\n<!-- Generated by `go run ./cmd/aitk __reference > docs/reference/cli.md`. Do not edit. -->\n\n")
	b.WriteString("Global flags: `--json` prints one `aitk.result/v1` object; `-C, --path <dir>` runs as if started in `<dir>`.\n")
	b.WriteString("Exit codes: 0 success · 1 runtime failure · 2 usage error · 3 gate rejected · 4 conflict.\n")
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		if c.Hidden || c.Name() == "help" || strings.HasPrefix(c.Name(), "__") {
			return
		}
		if c != root && c.Runnable() {
			fmt.Fprintf(&b, "\n## `%s`\n\n%s\n\n```\n%s\n```\n", c.CommandPath(), c.Short, c.UseLine())
			if fl := strings.TrimRight(c.LocalNonPersistentFlags().FlagUsages(), "\n"); fl != "" {
				b.WriteString("\n```\n" + fl + "\n```\n")
			}
		}
		subs := c.Commands()
		sort.Slice(subs, func(i, j int) bool { return subs[i].Name() < subs[j].Name() })
		for _, s := range subs {
			walk(s)
		}
	}
	walk(root)
	return b.String()
}
