// Package handoff writes per-session handoff files and the generated index.
package handoff

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/innaka-tech/ai-toolkit/v2/internal/doc"
	"github.com/innaka-tech/ai-toolkit/v2/internal/fsx"
	"github.com/innaka-tech/ai-toolkit/v2/internal/project"
	"github.com/innaka-tech/ai-toolkit/v2/internal/schema"
	"github.com/innaka-tech/ai-toolkit/v2/internal/task"
	"github.com/innaka-tech/ai-toolkit/v2/internal/textx"
)

// Meta mirrors schemas/handoff.schema.json.
type Meta struct {
	Task       string      `yaml:"task,omitempty" json:"task,omitempty"`
	At         string      `yaml:"at" json:"at"`
	By         string      `yaml:"by" json:"by"`
	Outcome    string      `yaml:"outcome" json:"outcome"`
	TaskStatus string      `yaml:"task_status,omitempty" json:"task_status,omitempty"`
	Check      *task.Check `yaml:"check,omitempty" json:"check,omitempty"`
	Commits    []string    `yaml:"commits,omitempty" json:"commits,omitempty"`
	Files      []string    `yaml:"files,omitempty" json:"files,omitempty"`
	Next       []string    `yaml:"next,omitempty" json:"next,omitempty"`
	To         string      `yaml:"to,omitempty" json:"to,omitempty"`
}

// Handoff is a parsed handoff file.
type Handoff struct {
	Meta
	Body string `json:"body"`
	File string `json:"file"`
}

// Write creates docs/ai/handoff/<UTC>-<task>.md and refreshes the index.
func Write(p *project.Project, m Meta, body string) (*Handoff, error) {
	if err := schema.Validate("handoff", m); err != nil {
		return nil, err
	}
	stamp := strings.NewReplacer("-", "", ":", "").Replace(m.At)
	suffix := m.Task
	if suffix == "" {
		suffix = "project"
	}
	rel := filepath.ToSlash(filepath.Join(project.HandoffDir, stamp+"-"+suffix+".md"))
	for i := 2; fsx.Exists(p.Path(rel)); i++ {
		rel = filepath.ToSlash(filepath.Join(project.HandoffDir, fmt.Sprintf("%s-%s-%d.md", stamp, suffix, i)))
	}
	b, err := doc.Join(m, body)
	if err != nil {
		return nil, err
	}
	if err := fsx.WriteFile(p.Path(rel), b, 0o644); err != nil {
		return nil, err
	}
	if err := WriteIndex(p); err != nil {
		return nil, err
	}
	return &Handoff{Meta: m, Body: body, File: rel}, nil
}

// List returns handoffs newest first.
func List(p *project.Project) []*Handoff {
	entries, _ := os.ReadDir(p.Path(project.HandoffDir))
	var out []*Handoff
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		rel := filepath.ToSlash(filepath.Join(project.HandoffDir, e.Name()))
		b, err := os.ReadFile(p.Path(rel))
		if err != nil {
			continue
		}
		front, body, ok := doc.Split(string(b))
		if !ok {
			continue
		}
		h := &Handoff{Body: body, File: rel}
		if yaml.Unmarshal([]byte(front), &h.Meta) != nil {
			continue
		}
		out = append(out, h)
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].At != out[j].At {
			return out[i].At > out[j].At
		}
		return out[i].File > out[j].File
	})
	return out
}

// WriteIndex regenerates docs/ai/handoff.md (10 newest).
func WriteIndex(p *project.Project) error {
	hs := List(p)
	var b strings.Builder
	b.WriteString("# Handoffs\n\n<!-- Generated by aitk. Do not edit; handoffs live in docs/ai/handoff/. -->\n\n")
	if len(hs) == 0 {
		b.WriteString("No handoffs yet.\n")
	}
	for i, h := range hs {
		if i == 10 {
			fmt.Fprintf(&b, "\n%d older handoffs in docs/ai/handoff/.\n", len(hs)-10)
			break
		}
		fmt.Fprintf(&b, "- %s · %s · %s · %s — [%s](%s)\n", h.At, nz(h.Task, "project"), h.By, h.Outcome, textx.Truncate(nz(textx.FirstLine(h.Body), "(no summary)"), 100), strings.TrimPrefix(h.File, "docs/ai/"))
	}
	path := p.Path(project.DocsAI, "handoff.md")
	if old, err := os.ReadFile(path); err == nil && !strings.Contains(string(old), "<!-- Generated by aitk") {
		return nil // hand-written: never overwrite
	}
	return fsx.WriteFile(path, []byte(b.String()), 0o644)
}

func nz(s, d string) string {
	if s == "" {
		return d
	}
	return s
}
